# The name of the action, it is used for display in the actions view in GitHub
name: Build project using muddler and upload artifact

# This section controls when the action runs. In this case, when code is checked
# into the main branch or when a pull request is made targeting the main branch.
# If your projects default branch is something else, such as 'development'
# then you would use that instead of 'master' below
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# Including this lets your run the action on demand as well
  workflow_dispatch:
  
# The jobs (collection of steps) for the action
jobs:
  # This collection is called 'build'
  build:
    # build on GitHub's latest ubuntu image
    runs-on: ubuntu-latest

    # The steps to follow for the 'build' job
    steps:
      # this step checks out the project repository to work on
      - uses: actions/checkout@v3.3.0

      # this step is by demonnic, which builds your project with Muddler
      # it will show up as 'Muddle' in the GitHub web interface later
      - name: Muddle
        uses: demonnic/build-with-muddler@main
        with:
          muddlerVersion: LATEST
      
      # This step uploads the artifact for you and others to download
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # build/tmp/ is the directory muddler makes the mpackage out of
          # GitHub only allows you to upload zip files, so we let them
          # zip it up and upload it. That's all the .mpackage is anyway
          # just with a different file extension
          name: MorgenGrauen (${{ github.run_number }})
          path: build/tmp/
